server:
  port: 9000
spring:
  application:
    name: cloud-configuration
  cloud:
    config:
      server:
        git:
          uri:
#  rabbitmq: #RabbitMQ相关的配置
#    host: ${rabbitMQHost:127.0.0.1}
#    port: ${rabbitMQPort:5672}
#    username: ${rabbitMQUsername:guest}
#    password: ${rabbitMQPassword:guest}

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://ycs:1234@127.0.0.1:9999/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id

management:
  security:
    enabled: false #是否开启actuator安全认证
